spring:
  application:
    name: GestionReservas

  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_reservas
    username: postgres
    password: elliam012
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
        ddl-auto: update

  server:
    port: 8080
